/**
 * Vector data structure for storing document embeddings in Milvus
 */
export interface VectorData {
  pk?: number; // Auto-generated by Milvus (primary key)
  file_id: string; // References File.id from Prisma
  chunk_index: number; // Position of chunk in document (0-based)
  page_number?: number; // Optional page reference for PDFs
  chunk_strategy: string; // Chunking method used (e.g., 'fixed-size', 'semantic', 'paragraph')
  vector: number[]; // The embedding vector
  created_at: number; // Unix timestamp (milliseconds)
  embedding_version?: number; // Track embedding model version for future migrations
}

/**
 * Search result from vector similarity search
 */
export interface SearchResult {
  pk: number;
  file_id: string;
  chunk_index: number;
  page_number?: number;
  chunk_strategy: string;
  created_at: number;
  embedding_version?: number;
  distance: number; // Similarity score (lower is more similar for L2, higher for COSINE)
}

/**
 * Options for vector search operations
 */
export interface SearchOptions {
  topK?: number; // Number of results to return (default: 10)
  filter?: string; // Milvus filter expression (e.g., 'file_id == "abc123"')
  outputFields?: string[]; // Fields to include in results (default: all scalar fields)
  metricType?: 'L2' | 'IP' | 'COSINE'; // Distance metric (default: COSINE)
}

/**
 * Collection statistics
 */
export interface CollectionStats {
  rowCount: number;
  collectionName: string;
  dimension: number;
  indexType: string;
  metricType: string;
}

/**
 * Batch insert result
 */
export interface InsertResult {
  insertedCount: number;
  insertedIds: number[];
}

/**
 * Delete result
 */
export interface DeleteResult {
  deletedCount: number;
}
